# Project identification
sonar.projectKey=fitness_gym_frontend
sonar.projectName=Fitness Gym Frontend
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Host URL
sonar.host.url=http://localhost:9000

# Language & Coverage
# Ensure you run `ng test --code-coverage` to generate this report
sonar.javascript.lcov.reportPaths=coverage/fitness-gym-frontend/lcov.info

# Exclusions
sonar.exclusions=node_modules/**, dist/**, .angular/**, coverage/**
sonar.coverage.exclusions=**/*.spec.ts, main.ts, **/*.module.ts

# Encoding
sonar.sourceEncoding=UTF-8
